on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"


name: epick CI

jobs:

  test:
    name: Test Suite
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/test
